DotNetAppSqlDb/Models/Todo.cs
using System;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Web;

namespace DotNetAppSqlDb.Models
{
    public class Todo
    {
        public int ID { get; set; }

        [DisplayName("Product Name")]
        public string Name { get; set; }
        [DisplayName("Product Description")]
        public string Description { get; set; }

        public string ThumbnailPath { get; set; }

        [Display(Name = "Created Date")]
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        public DateTime CreatedDate { get; set; }

        [DisplayName("Upload File")]
        public string ImagePath { get; set; }
        [NotMapped]
        public HttpPostedFileBase ImageFile { get; set; }
    }
}

DotNetAppSqlDb/Controllers/TodosController.cs
using System;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using DotNetAppSqlDb.Models;
using System.Diagnostics;
using System.IO;
using Azure.Storage.Blobs;
using Azure.Storage.Blobs.Models;
using System.Configuration;
using Azure.Storage.Queues;
using Microsoft.WindowsAzure.Storage.Queue;
using Microsoft.WindowsAzure.Storage;
using Newtonsoft.Json;

namespace DotNetAppSqlDb.Controllers
{
    public class TodosController : Controller
    {
        private MyDatabaseContext db = new MyDatabaseContext();

        // GET: Todos
        public ActionResult Index()
        {            
            Trace.WriteLine("GET /Todos/Index");
            return View(db.Todoes.ToList());
        }

        // GET: Todos/Details/5
        public ActionResult Details(int? id)
        {
            Trace.WriteLine("GET /Todos/Details/" + id);
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Todo todo = db.Todoes.Find(id);
            if (todo == null)
            {
                return HttpNotFound();
            }
            return View(todo);
        }

        // GET: Todos/Create
        public ActionResult Create()
        {
            Trace.WriteLine("GET /Todos/Create");
            return View(new Todo { CreatedDate = DateTime.Now });
        }

        [HttpPost]
        public ActionResult Create([Bind(Include = "Description,CreatedDate,Name,ImagePath,ThumbnailPath,ImageFile")] Todo todo)
        {
            try
            {
                Trace.WriteLine("POST /Todos/Create");
                if (ModelState.IsValid)
                {
                    //var temp = Request.Files.Count;
                    //HttpPostedFileBase file = Request.Files["ImageData"];
                    //int i = UploadImageInDataBase(file, todo);
                    if (Request.Files.AllKeys.Any())
                    {
                        // Get the uploaded image from the Files collection
                        var httpPostedFile = HttpContext.Request.Files[0];

                        if (httpPostedFile != null)
                        {
                        }
                    }
                    db.Todoes.Add(todo);
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }

                return View(todo);
            }
            catch (Exception ex)
            {
                ViewBag.Message = "Some exception has occurred, Sorry! : " + ex.Message;
                return null;
            }
        }

        private int UploadImageInDataBase(HttpPostedFileBase file, Todo todo)
        {
            todo.ImagePath = null; // ConvertToBytes(file);
            //var Content = new Content
            //{
            //    Title = contentViewModel.Title,
            //    Description = contentViewModel.Description,
            //    Contents = contentViewModel.Contents,
            //    Image = contentViewModel.Image
            //};
            db.Todoes.Add(todo);
            int i = db.SaveChanges();
            return (i == 1) ? 1 : 0;            
        }
        private byte[] ConvertToBytes(HttpPostedFileBase image)
        {
            byte[] imageBytes = null;
            BinaryReader reader = new BinaryReader(image.InputStream);
            imageBytes = reader.ReadBytes((int)image.ContentLength);
            return imageBytes;
        }
        // GET: Todos/Edit/5
        public ActionResult Edit(int? id)
        {
            Trace.WriteLine("GET /Todos/Edit/" + id);
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Todo todo = db.Todoes.Find(id);
            if (todo == null)
            {
                return HttpNotFound();
            }
            return View(todo);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "id,Name,Description,CreatedDate")] Todo todo)
        {
            Trace.WriteLine("POST /Todos/Edit/" + todo.ID);
            if (ModelState.IsValid)
            {
                db.Entry(todo).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(todo);
        }

        // GET: Todos/Delete/5
        public ActionResult Delete(int? id)
        {
            Trace.WriteLine("GET /Todos/Delete/" + id);
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Todo todo = db.Todoes.Find(id);
            if (todo == null)
            {
                return HttpNotFound();
            }
            return View(todo);
        }

        // POST: Todos/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Trace.WriteLine("POST /Todos/Delete/" + id);
            Todo todo = db.Todoes.Find(id);
            db.Todoes.Remove(todo);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        [HttpGet]
        public ActionResult Upload(int id)
        {
            Trace.WriteLine("POST /Todos/Upload/" + id);
            Todo todo = db.Todoes.Find(id);            
            return View(todo);
        }
        [HttpPost, ActionName("Upload")]
        public ActionResult Upload([Bind(Include = "ID")] Todo todo, HttpPostedFileBase uploadedImage)
        {
            try
            {
                if (uploadedImage.ContentLength > 0)
                {
                    string imageFileName = Path.GetFileName(uploadedImage.FileName);
                    string folderPath = Path.Combine(Server.MapPath("~/UploadedImages"), imageFileName);
                    uploadedImage.SaveAs(folderPath);
                    string connectionString = ConfigurationManager.AppSettings["storageAccountConnectionString"];

                    BlobServiceClient blobSvcClient = new BlobServiceClient(connectionString);
                    BlobContainerClient container = CreateContainer(blobSvcClient, "products-container", true);
                    BlobClient uploadedBlob = UploadBlob(container, folderPath);
                    BlobContainerProperties props = container.GetProperties();
                    string allMetadata = string.Empty;
                    foreach (var item in props.Metadata)
                    {
                        allMetadata = allMetadata + item.Key + " - " + item.Value + "\n";
                    }
                    string finalMetadata = allMetadata;
                    //ListBlobs(container);
                    //ListBlobs(container);
                    //ListBlobsAsAnonimousUser("con2");
                    //LeaseDemo(con1);
                    //CreateServiceSASforBlobContainer(con1);
                    //BlobClient blobClient = con1.GetBlobClient("shoes-2.png");
                    //CreateServiceSASforBlob(blobClient);
                    //string policyName = "PolicyOne";
                    //CreateStoredAccessPolicy(con1, policyName);
                    //CreateServiceSASforBlob(blobClient, policyName);
                    //}

                    if (ModelState.IsValid)
                    {
                        Todo fromDb = db.Todoes.Find(todo.ID);
                        fromDb.ImagePath = uploadedBlob.Uri.AbsoluteUri;
                        db.Entry(fromDb).State = EntityState.Modified;
                        db.SaveChanges();
                    }
                    PostMessageInQueue(connectionString, todo.ID, uploadedBlob.Uri.AbsoluteUri);
                    return RedirectToAction("Index");
                }
            }
            catch (Exception exception)
            {
                ViewBag.Message = "Some Error was thrown while uploading file to blob storage" + exception.Message;
            }

            return View(todo);
        }

        private static void PostMessageInQueue(string connectionString, int id, string uri)
        {
            CloudQueueClient cloudQueueClient = CloudStorageAccount.Parse(connectionString).CreateCloudQueueClient();
            CloudQueue thumbnailRequestQueue = cloudQueueClient.GetQueueReference("productsqueue");
            thumbnailRequestQueue.CreateIfNotExists();
            BlobInformation blobInfo = new BlobInformation() { Id = id, BlobUri = new Uri(uri) };
            var queueMessage = new CloudQueueMessage(JsonConvert.SerializeObject(blobInfo));
            thumbnailRequestQueue.AddMessage(queueMessage);
        }

        private BlobContainerClient CreateContainer(BlobServiceClient blobSvcClient, string containerName, bool isPublic)
        {
            BlobContainerClient container = blobSvcClient.GetBlobContainerClient(containerName);
            if (!container.Exists())
            {
                container.Create();
                Console.WriteLine($"{containerName} is Created\n");
                if (isPublic)
                {
                    container.SetAccessPolicy(PublicAccessType.Blob);
                }
            }
            return container;
        }

        private BlobClient UploadBlob(BlobContainerClient container, string path)
        {
            FileInfo fi = new FileInfo(path);
            BlobClient blobClient = container.GetBlobClient(fi.Name);
            if (!blobClient.Exists())
            {
                Azure.Response<BlobContentInfo> temp = blobClient.Upload(path);
            }
            return blobClient;
        }

DotNetAppSqlDb/Views/Todos/Create.cshtml
@model DotNetAppSqlDb.Models.Todo

@{ ViewBag.Title = "Create"; }

<h2>Create</h2>


@using (Html.BeginForm())
{
@Html.AntiForgeryToken()

<div class="form-horizontal">
    <h4>A Product</h4>
    <hr />
    @Html.HiddenFor(model => model.ID)
    @*<div class="form-group">
            @Html.LabelFor(model => model.ID, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ID, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ID, "", new { @class = "text-danger" })
            </div>
        </div>*@

    <div class="form-group">
        @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
        </div>
    </div>

    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
        </div>
    </div>


    @*@using (Html.BeginForm("Upload","Todos",FormMethod.Post, new { enctype = "multipart/form-data" }))
    {
        <div class="form-group">
            @Html.LabelFor(model => model.ImagePath, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input type="file" name="file" required />
                <input type="submit" value="Upload" />
            </div>
        </div>
    }*@


    @*<div class="form-group">
        @Html.LabelFor(model => model.ThumbnailPath, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.ThumbnailPath, new
            {
                htmlAttributes = new
                {
                    @class = "form-control",
                    disabled = "disabled",
                    @readonly = "readonly"
                }
            })
            @Html.ValidationMessageFor(model => model.ThumbnailPath, "", new { @class = "text-danger" })
        </div>
    </div>*@

    <div class="form-group">
        @Html.LabelFor(model => model.CreatedDate, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.CreatedDate, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.CreatedDate, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Create" />
        </div>
    </div>
</div>}

<div>
    @Html.ActionLink("Back to Products", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

DotNetAppSqlDb/Views/Todos/Delete.cshtml
@model DotNetAppSqlDb.Models.Todo

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Todo</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.ID)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ID)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>
       
        <dt>
            @Html.DisplayNameFor(model => model.ImagePath)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ImagePath)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.ThumbnailPath)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ThumbnailPath)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.CreatedDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CreatedDate)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

DotNetAppSqlDb/Views/Todos/Details.cshtml
@model DotNetAppSqlDb.Models.Todo

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Todo</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.ID)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ID)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>
       
        <dt>
            @Html.DisplayNameFor(model => model.ThumbnailPath)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ThumbnailPath)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.CreatedDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CreatedDate)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.ID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

DotNetAppSqlDb/Views/Todos/Edit.cshtml
@model DotNetAppSqlDb.Models.Todo

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <h4>Modify a product</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.ID)

    <div class="form-group">
        @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.ThumbnailPath, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.ThumbnailPath, new
            {
                htmlAttributes = new
                {
                    @class = "form-control",
                    disabled = "disabled",
                    @readonly = "readonly"
                }
            })
            @Html.ValidationMessageFor(model => model.ThumbnailPath, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.CreatedDate, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.CreatedDate, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.CreatedDate, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Save" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

DotNetAppSqlDb/Views/Todos/Index.cshtml
@model IEnumerable<DotNetAppSqlDb.Models.Todo>

@{
    ViewBag.Title = "Index";
}

<h2>Products Catalog</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Description)
        </th>        
        <th>
            @Html.DisplayNameFor(model => model.ImagePath)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ThumbnailPath)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.CreatedDate)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
<tr>
    <td>
        @Html.DisplayFor(modelItem => item.Name)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.Description)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.ImagePath)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.ThumbnailPath)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.CreatedDate)
    </td>
    <td>
        @Html.ActionLink("Edit", "Edit", new { id = item.ID }) |
        @Html.ActionLink("Upload", "Upload", new { id = item.ID }) |
        @Html.ActionLink("Details", "Details", new { id = item.ID }) |
        @Html.ActionLink("Delete", "Delete", new { id = item.ID })
    </td>
</tr>
}

</table>

DotNetAppSqlDb/Views/Todos/Upload.cshtml
@model DotNetAppSqlDb.Models.Todo

@{
    ViewBag.Title = "Upload";
}

<h2>Upload</h2>


@using (Html.BeginForm("Upload", "Todos", FormMethod.Post, new { enctype = "multipart/form-data" }))
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">
            <h4>Upload a file which will be stored in blob storage and will be converted into a thumbnail</h4>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            @Html.HiddenFor(model => model.ID)

            <div class="form-group">
                @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Name, new
                    {
                        htmlAttributes = new
                        {
                            @class = "form-control",
                            disabled = "disabled",
                            @readonly = "readonly"
                        }
                    })
                    @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                </div>
            </div>


            <div class="form-group">
                @Html.LabelFor(model => model.ImagePath, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">                    
                    @Html.TextBox("uploadedImage", "", new { type = "File" })
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Upload" class="btn btn-default" />
                </div>
            </div>

        </div>
    }

    <div>
        @Html.ActionLink("Back to List", "Index")
    </div>

    @section Scripts {
        @Scripts.Render("~/bundles/jqueryval")
    }